services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./seed:/seed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Comment out the following section if you want to use a local .NET application instead
  dotnet_app:
    image: andreashf/healthtech-sample:backend
    # build:
    #   context: ./src/Backend
    #   dockerfile: Dockerfile
    ports:
      - "5063:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=timescaledb;Port=5432;Database=mydb;Username=postgres;Password=postgres"
    container_name: dotnet_app
    depends_on:
      timescaledb:
        condition: service_healthy

  frontend:
    build: 
      context: .
    container_name: frontend
    ports:
      - "8080:3000"
    depends_on:
      - dotnet_app
      - timescaledb

volumes:
  timescale_data: